config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  resources :users, only: %i[show edit update]
  resources :rooms, only: %i[show create], param: :title
  resources :messages, only: :create do
    member { post :like }
  end

  root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :message, counter_cache: true
end

app/models/message.rb
class Message < ApplicationRecord
  has_many :likes, dependent: :destroy

  belongs_to :user
  belongs_to :room

  scope :sorted, -> { order(:id) }

  validates :body, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, -> { sorted }, dependent: :destroy

  belongs_to :user

  before_create { self.title = SecureRandom.hex(3) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:email, :password, :name, :surname, :phone_number, :password, :about)
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @new_message = current_user.messages.build(strong_params)

    if @new_message.save
      room = @new_message.room
      @new_message.broadcast_append_to room, target: "room_#{room.id}_messages", locals: { user: current_user, message: @new_message.decorate }
    end
  end

  def like
    @message = Message.find(params[:id])
    like = @message.likes.find_by(user: current_user)

    if like.present?
      like.destroy
    else
      @message.likes.create(user: current_user)
    end

    room = @message.room

    @message.broadcast_replace_to [current_user, room], target: "message_like_#{@message.id}", partial: "messages/heart", locals: { user: current_user, message: @message.decorate }
    @message.broadcast_replace_to room, target: "message_likes_count_#{@message.id}", partial: "messages/likes_count", locals: { user: current_user, message: @message.decorate }
  end

  private

  def strong_params
    params.require(:message).permit(:body, :room_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def name

  end

  private

  def after_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @new_room = Room.new
    @rooms = Room.all
  end

  def show
    @room = Room.find_by!(title: params[:title])
    @messages = MessageDecorator.decorate_collection(@room.messages.includes(:user))
    @new_message = current_user&.messages&.build(room: @room)
  end

  def create
    @new_room = Room.new(user: current_user)

    @new_room.broadcast_append_to :rooms if @new_room.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_likes = Like.where(user_id: @user.id)

    @user_messages = MessageDecorator.decorate_collection(
      Message.includes(:likes)
        .where(user_id: @user.id)
        .where('messages.user_id' == 'likes.user_id')
        .where('messages.id' == 'likes.message_id')
        .sort_by(&:likes_count)
        .reverse
    )
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_permited_params)

    redirect_to user_path(@user)
  end

  def user_permited_params
    params.require(:user).permit(:name, :surname, :phone_number, :about)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotwire Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="min-h-full">
      <nav class="bg-gray-800">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="flex items-center justify-between h-16">
            <div class="flex items-center">
              <div class="flex-shrink-0">
                <a href="/">
                  <img class="h-8 w-8" src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow">
                </a>
              </div>
              <div class="hidden md:block">
                <div class="ml-10 flex items-baseline space-x-4">
                  <h1 class="text-2xl font-bold text-white">Hotwire Chat</h1>
                  <% if current_user.present? %>
                    <%= link_to "Profile", user_path(current_user), class: "text-gray-300
                      hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium
                      "%>
                    <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete },
                      class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                    %>
                  <% else %>
                    <%= link_to "Sign in", new_user_session_path, class: "text-gray-300
                      hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium
                      "%>
                    <%= link_to "Sign up", new_user_registration_path, class: "text-gray-300
                      hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium
                      "%>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="md:hidden" id="mobile-menu">
          <h1 class="text-2xl font-bold text-white">Hotwire Chat</h1>
          <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
            <% if current_user.present? %>
              <%= link_to "Profile", user_path(current_user), class: "text-gray-300
                hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium
              "%>
              <%= link_to "Sign out", destroy_user_session_path, data: { "turbo-method": :delete },
                class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
              %>
            <% else %>
              <%= link_to "Sign in", new_user_session_path, class: "text-gray-300
                hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium
                "%>
              <%= link_to "Sign up", new_user_registration_path, class: "text-gray-300
                hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium
                "%>
            <% end %>
          </div>
        </div>
      </nav>

      <main>
        <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
          <%= yield %>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/messages/_heart.html.erb
<span id="message_like_<%= message.id %>"><%= message.heart(user) %></span>

app/views/messages/_likes_count.html.erb
<span id="message_likes_count_<%= message.id %>"><%= message.likes_count %></span>

app/views/messages/_message.html.erb
<div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg my-4 py-2 pl-1">
  <div class="flex flex-row">
    <div class="basis-1/12"><%= l(message.created_at, format: :short) %></div>
    <div class="basis-3/12 text-center">
      <%= turbo_frame_tag message.user do%>
        <%= render message.user %>
      <% end %>
    </div>
    <div class="basis-7/12"><%= message.body %></div>
    <div class="basis-1/12">
      <%= link_to like_message_path(message), data: { "turbo-method": :post } do %>
        <%= render partial: "messages/heart", locals: { user: current_user, message: message } %>
        <%= render partial: "messages/likes_count", locals: { message: message } %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/_room.html.erb
<%= link_to room.title, room_path(room.title), class: "text-current text-blue-500 mr-4", target: "_blank", rel: "noopener noreferrer" %>

app/views/rooms/index.html.erb
<%= turbo_stream_from :rooms %>

<%= turbo_frame_tag :rooms do %>
  <%= render @rooms %>
<% end %>

<% if current_user.present? %>
  <%= form_with model: @new_room, class: "mt-4" do |f| %>
    <div class="flex flex-row">
      <%= f.submit "Create room", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 cursor-pointer basis-1/12" %>
  <% end %>
<% end %>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>
<%= turbo_stream_from [current_user, @room] %>

<div class="flex flex-col h-96 justify-between">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8" id="chat-container">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8" id="room_<%= @room.id %>_messages">
      <%= render partial: "messages/message", collection: @messages, locals: { user: current_user } %>
    </div>
  </div>
</div>

<% if current_user.present? %>
  <%= form_with model: @new_message, data: { controller: "chat_refresh", action: "turbo:submit-end->chat_refresh#clearInput" } do |f| %>
    <div class="rounded-md shadow-sm -space-y-px">
      <%= f.text_field :body, autofocus: true, required: true, placeholder: "Your text", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
      <%= f.hidden_field :room_id, value: @room.id %>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<%= link_to "#{user.name} #{user.surname[0]}.", user_path(user), class: "text-current text-blue-500 mr-4", target: "_blank", rel: "noopener noreferrer" %>

app/views/users/edit.html.erb
<div class="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-2xl font-bold text-gray-900">
        Edit your profile
      </h2>
    </div>
    <%= form_for @user do |f| %>
      <div class="rounded-md shadow-sm -space-y-px">
        <div>
          <%= f.label :name, class: "sr-only" %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", required: true, placeholder: "Name", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
        </div>
        <div>
          <%= f.label :surname, class: "sr-only" %>
          <%= f.text_field :surname, autofocus: true, autocomplete: "surname", required: true, placeholder: "Surname", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
        </div>
        <div>
          <%= f.label :phone_number, class: "sr-only" %>
          <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number", placeholder: "Phone Number", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
        </div>
        <div>
          <%= f.label :about, class: "sr-only" %>
          <%= f.text_field :about, autofocus: true, autocomplete: "about", placeholder: "About", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
        </div>
      </div>

      <div>
        <%= f.submit "Edit profile", class: "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 cursor-pointer" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="bg-white shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6 flex flex-row">
    <h3 class="text-lg leading-6 font-medium text-gray-900 basis-11/12">Profile</h3>
    <% if current_user.id == @user.id %>
      <%= button_to "Edit profile", edit_user_path(current_user), method: :get, class: "text-white hover:bg-gray-700
        hover:text-white px-3 py-2 basis-1/12 bg-indigo-600 hover:bg-indigo-700 rounded-md text-sm font-medium
        "%>
    <% end %>
  </div>
  <div class="border-t border-gray-200">
    <dl>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Full name</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"> <%= @user.surname %> <%= @user.name %> </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Email address</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"> <%= @user.email %> </dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Phone number</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"><%= @user.phone_number %></dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">About</dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2"> <%= @user.about %> </dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <div class="text-sm font-medium text-gray-500">User messages:</div>
      </div>
      <div class="flex flex-col h-96 justify-between">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8" id="chat-container">
          <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8" id="user_<%= @user.id %>_user_messages">
            <%= render partial: "messages/message", collection: @user_messages, locals: { user: @user } %>
          </div>
        </div>
      </div>
    </dl>
  </div>
</div>